In [1]:
import pandas as pd
import numpy as np
from scipy.sparse import csr_matrix, coo_matrix

In [2]:
## Lets make two simple arrays. A dapi array with two cells, labelled 2 and 7
## and a microglia array. The shape of the process has label 5
## I want to find if the two shapes overlap and if they do then to get the mapping

dapi = [
    [2, 2, 0, 0, 7],
    [2, 2, 0, 7, 7],
    [0, 0, 0, 0, 0]
]

microglia = [
    [0, 0, 5, 0, 0],
    [0, 5, 0, 0, 0],
    [0, 0, 5, 5, 0]
]

In [3]:
# Convert the array to parse matrices
dapi_csr = csr_matrix(dapi)
microglia_csr = csr_matrix(microglia)

In [4]:
# dapi_csr[microglia_coo.row, microglia_coo.col]

In [5]:
# The labels are kept under .data
microglia_csr.data

array([5, 5, 5, 5])

In [6]:
# and this is the row, col location of the non zero elements
microglia_csr.nonzero()

(array([0, 1, 2, 2], dtype=int32), array([2, 1, 2, 3], dtype=int32))

In [7]:
# interogate now dapi. Does it have any labels where the microglia shape have been drawn
dapi_csr[microglia_csr.nonzero()]

matrix([[0, 2, 0, 0]])

In [8]:
# Q: ok why do I have an array of length 5?
# A: Because the microglia shape you are asking about has an area of 4. You are asking about 4 pixels
# 
# Q: ah ok. can i see the labels of those 4 pixels (the label of the microglia)?
# A: yes, here you are:

In [9]:
microglia_csr.data

array([5, 5, 5, 5])

In [10]:
# Q: Ah nice, so my microglia shape has 4 pixels. And if i overlap my microglia to my dapi
# those 4 pixels correspond to the background on the dapi side appart from one which falls
# inside the nuclei with label 2?
# A: yes exactly. What you can do get of the zeros and end up with something like:
# 
#--------------------------------
# dapi_label    microglia_label
#      2             5
#--------------------------------
#